language: objective-c
osx_image: xcode61
before_install:
    - git submodule init
    - git submodule update
    - git submodule init CocoaAsyncSocket
    - git submodule update CocoaAsyncSocket
    - cd CocoaAsyncSocket
    - git clone https://github.com/colemancda/CocoaLumberjack.git
    - cd ../
script:
    - cd CocoaAsyncSocket
    - cd CocoaLumberjack
    - git status
    - cd Framework
    - cd Desktop
    - xcodebuild -project Lumberjack.xcodeproj -scheme 'CocoaLumberjack' -sdk macosx -arch x86_64 build
    - cd ../../../
    - xcodebuild -project Framework/CocoaAsyncSocket/CocoaAsyncSocket.xcodeproj -scheme 'CocoaAsyncSocket' -sdk macosx -arch x86_64 build CODE_SIGNING_REQUIRED=NO
    - cd ../
    - xcodebuild -project Framework/CocoaHTTPServer/CocoaHTTPServer.xcodeproj -scheme 'CocoaHTTPServer' -sdk macosx -arch x86_64 build CODE_SIGNING_REQUIRED=NO