language: objective-c
osx_image: xcode61
before_install: true
script:
    - xcodebuild -project Framework/CocoaHTTPServer/CocoaHTTPServer.xcodeproj CODE_SIGNING_REQUIRED=NO -scheme 'CocoaHTTPServer' test